id: untriaged
name: GitOps.PullRequestIssueManagement
description: Manage the 'untriaged' label on issues
resource: repository

configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
    - description: Add untriaged label to new/reopened issues without a milestone
      if:
      - payloadType: Issues
      - isOpen
      - not:
          isPartOfAnyMilestone
      - or:
        - isAction:
            action: Opened
        - isAction:
            action: Reopened
      - not:
          hasLabel:
            label: untriaged
      then:
      - addLabel:
          label: untriaged

    - description: Remove untriaged label from issues when closed or added to a milestone
      if:
      - payloadType: Issues
      - or:
        - isAction:
            action: Closed
        - isPartOfAnyMilestone
      - hasLabel:
          label: untriaged
      then:
      - removeLabel:
          label: untriaged
