parameters:
  agentOs: ''
  queue: {}
  variables: {}

phases:
- template: /eng/common/templates/phases/base.yml
  parameters:
    name: ${{ parameters.agentOs }}
    enableTelemetry: true
    enableMicrobuild: true
    publicBuildReasons: PullRequest
    queue: ${{ parameters.queue }}
    variables: 
      ${{ insert }}: ${{ parameters.variables }}
      _HelixType: build/product
      _HelixBuildConfig: $(_BuildConfig)
      ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
        _HelixSource: pr/dotnet/CliCommandLineParser/$(Build.SourceBranch)
        _OfficialBuildIdArgs: ''
        _PublishArgs: ''
        _SignArgs: ''
      ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
        _HelixSource: official/dotnet/CliCommandLineParser/$(Build.SourceBranch)
        _OfficialBuildIdArgs: /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
        _PublishArgs: /p:DotNetPublishBlobFeedKey=$(dotnetfeed-storage-access-key-1)
                  /p:DotNetPublishBlobFeedUrl=$(PB_PublishBlobFeedUrl)
                  /p:DotNetPublishToBlobFeed=$(_DotNetPublishToBlobFeed)
                  /p:DotNetSymbolServerTokenMsdl=$(microsoft-symbol-server-pat)
                  /p:DotNetSymbolServerTokenSymWeb=$(symweb-symbol-server-pat)
                  /p:PB_PublishType=$(_PublishType)
        _SignArgs: /p:DotNetSignType=$(_SignType) /p:TeamName=$(_TeamName)

    steps:
    - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
      - task: AzureKeyVault@1
        inputs:
          azureSubscription: 'HelixProd_KeyVault'
          KeyVaultName: HelixProdKV
          SecretsFilter: 'HelixApiAccessToken'
        condition: always()        
      - task: AzureKeyVault@1
        inputs:
          azureSubscription: 'DotNet-Engineering-Services_KeyVault'
          KeyVaultName: EngKeyVault
          SecretsFilter: 'dotnetfeed-storage-access-key-1,microsoft-symbol-server-pat,symweb-symbol-server-pat'
        condition: succeeded()

    - ${{ if eq(parameters.agentOs, 'Windows_NT') }}:
      - script: eng\common\CIBuild.cmd 
                  -configuration %BuildConfig%
                  $(_PublishArgs)
                  $(_SignArgs)
                  $(_OfficialBuildIdArgs)
        displayName: Build
        env:
          BuildConfig: $(_BuildConfig)
          BlobFeedUrl: $(PB_PublishBlobFeedUrl)
          PublishType: $(_PublishType)

    - ${{ if ne(parameters.agentOs, 'Windows_NT') }}:
      - script: eng/common/cibuild.sh 
                  --configuration $BuildConfig
                  $(_PublishArgs)
                  $(_SignArgs)
                  $(_OfficialBuildIdArgs)
        displayName: Build
        env:
          BuildConfig: $(_BuildConfig)
          BlobFeedUrl: $(PB_PublishBlobFeedUrl)
          PublishType: $(_PublishType)

    - task: PublishTestResults@1
      displayName: Publish Test Results
      inputs:
        testRunner: XUnit
        testResultsFiles: 'artifacts/TestResults/$(_BuildConfig)/*.xml'
        testRunTitle: '$(_AgentOSName)_$(Agent.JobName)'
        platform: '$(BuildPlatform)'
        configuration: '$(_BuildConfig)'
      condition: not(succeeded())

    - task: CopyFiles@2
      displayName: Gather Logs
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
         artifacts/log/$(_BuildConfig)/**/*
         artifacts/TestResults/$(_BuildConfig)/**/*
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      continueOnError: true
      condition: not(succeeded())

    - task: PublishBuildArtifacts@1
      displayName: Publish Logs to VSTS
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '$(_AgentOSName)_$(Agent.JobName)_$(Build.BuildNumber)'
        publishLocation: Container
      continueOnError: true
      condition: not(succeeded())
